apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cm-operator
  template:
    metadata:
      labels:
        name: cm-operator
    spec:
      serviceAccountName: cm-operator
      containers:
        - name: cm-operator
          # Replace this with the built image name
          image: neoseele/cm-operator:v0.0.1
          command:
          - cm-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 300m
              memory: 300Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cm-operator"
